<a href="https://colab.research.google.com/github/vivsingh119/agentic-ai-practise/blob/master/3-encoding_nominal_onehotencoder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd;
from sklearn.preprocessing import OneHotEncoder

**Types of Categorical Data :**

**Nominal Categorical Data**
---
This is a type of categorical data
which is used to identify an object
uniquely without providing any additional information. We cannot rank them naturally.
Example:
     Names of Cities
     Name of a person.

**Ordinal Categorical Data**:
---
This is type of categorical data
which can be ranked naturally.
Example:
    Education Level, School Grades, Seniority Level
    Post Graduate School Graduate PhD
    
rank: PhD, Post Graduate, Graduate, School

In [2]:
df_township=pd.read_csv("https://raw.githubusercontent.com/vivsingh119/agentic-ai-practise/refs/heads/master/township.csv")
df_township

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [3]:
df_township.columns

Index(['town', 'area', 'price'], dtype='object')

In [4]:
df_township.dtypes

town     object
area      int64
price     int64
dtype: object

In [5]:
df_township['town'].unique()

array(['monroe township', 'west windsor', 'robinsville'], dtype=object)

In [6]:
df_township['town'].isna().sum()

np.int64(0)

In [7]:
ohe=OneHotEncoder()

In [9]:
ohe.fit(df_township[['town']])

OneHotEncoder()

In [11]:
ohe.transform(df_township[['town']])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 13 stored elements and shape (13, 3)>

In [17]:
encoded_df=ohe.transform(df_township[['town']]).toarray()
encoded_df

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [15]:
ohe.categories_

[array(['monroe township', 'robinsville', 'west windsor'], dtype=object)]

In [21]:
df_new=pd.DataFrame(encoded_df,columns=ohe.categories_,dtype=int)
df_new

   monroe township robinsville west windsor
0                1           0            0
1                1           0            0
2                1           0            0
3                1           0            0
4                1           0            0
5                0           0            1
6                0           0            1
7                0           0            1
8                0           0            1
9                0           1            0
10               0           1            0
11               0           1            0
12               0           1            0

In [22]:
pd.concat([df_township,df_new],axis=1)

,town,area,price,"(monroe township,)","(robinsville,)","(west windsor,)"
0,monroe township,2600,550000,1,0,0
1,monroe township,3000,565000,1,0,0
2,monroe township,3200,610000,1,0,0
3,monroe township,3600,680000,1,0,0
4,monroe township,4000,725000,1,0,0
5,west windsor,2600,585000,0,0,1
6,west windsor,2800,615000,0,0,1
7,west windsor,3300,650000,0,0,1
8,west windsor,3600,710000,0,0,1
9,robinsville,2600,575000,0,1,0
10,robinsville,2900,600000,0,1,0
11,robinsville,3100,620000,0,1,0
12,robinsville,3600,695000,0,1,0