<a href="https://colab.research.google.com/github/vivsingh119/agentic-ai-practise/blob/master/8_ANN_Example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
churn_modelling=pd.read_csv("https://raw.githubusercontent.com/vivsingh119/agentic-ai-practise/refs/heads/master/Churn_Modelling.csv")

In [3]:
churn_modelling.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
#drop unwanted feature

In [5]:
data=churn_modelling.drop(columns=["CustomerId","RowNumber","Surname"],axis=1)

In [6]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [7]:
# encode categorical feature ,above dataset have two categorical featur i.e; Geography and Gender

In [42]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder ,StandardScaler

In [9]:
gender_encoder= LabelEncoder();
gender_encoded=gender_encoder.fit_transform(data["Gender"])
gender_encoded

array([0, 0, 0, ..., 0, 1, 0])

In [10]:
data['Gender']=gender_encoded

In [11]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [12]:
ohe=OneHotEncoder()

In [14]:
encoded_geography=ohe.fit_transform(data[["Geography"]])

In [15]:
encoded_geography.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [49]:
geography_new=pd.DataFrame(encoded_geography.toarray(),columns=ohe.get_feature_names_out(["Geography"]),dtype='int')

In [50]:
newData=pd.concat([data,geography_new],axis=1)

In [51]:
newData.drop(columns=["Geography"],axis=1,inplace=True)

In [59]:
newData

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1,0,0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0,0,1
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1,0,0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1,0,0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1,0,0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1,0,0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1,0,0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0,1,0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1,0,0

In [26]:
#train test data

In [27]:
from sklearn.model_selection import train_test_split

In [60]:
## DiVide the dataset into indepent and dependent features
X=newData.drop(columns=["Exited"],axis=1)
y=newData['Exited']

In [61]:
X

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,0,0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0,1
2,502,0,42,8,159660.80,3,1,0,113931.57,1,0,0
3,699,0,39,1,0.00,2,0,0,93826.63,1,0,0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,1,0,0
9996,516,1,35,10,57369.61,1,1,1,101699.77,1,0,0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,0,0
9998,772,1,42,3,75075.31,2,1,0,92888.52,0,1,0
9999,792,0,28,4,130142.79,1,1,0,38190.78,1,0,0

In [62]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [63]:

## Split the data in training and tetsing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=21)

In [64]:
#scale the feature
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [65]:
X_train

array([[ 1.40607594,  0.91094795, -0.66301688, ...,  0.99600797,
        -0.57831252, -0.57330877],
       [-1.19981741, -1.09775756,  0.96061996, ...,  0.99600797,
        -0.57831252, -0.57330877],
       [-0.38289053, -1.09775756, -1.42708127, ...,  0.99600797,
        -0.57831252, -0.57330877],
       ...,
       [-1.87197245,  0.91094795, -0.18547663, ..., -1.00400803,
        -0.57831252,  1.74426078],
       [ 0.47539974,  0.91094795,  0.38757166, ..., -1.00400803,
         1.72916886, -0.57330877],
       [ 2.06789013, -1.09775756, -1.33157322, ..., -1.00400803,
         1.72916886, -0.57330877]])